export enum CartActionTypes {
  ADD_PRODUCT = "cart/addProduct",
  // HANDLE_CART = "HANDLE_CART",
  REMOVE_PRODUCT_FROM_CART = "cart/removeProductFromCart",
  // CHECKOUT_INCREASE_ITEM_QUANTITY = "CHECKOUT_INCREASE_ITEM_QUANTITY",
  // CHECKOUT_DECREASE_ITEM_QUANTITY = "CHECKOUT_DECREASE_ITEM_QUANTITY",
  // EMPTY_CART = "EMPTY_CART",
  INCREASE_PRODUCT_QUANTITY = "cart/increaseProductQuantity",
}
